print("----------------Q1----------------")
bottles <- read.csv("data/bottles.data")
t.test(bottles , mu = 500 , alternative = "less")
t.test(bottles , mu = 500 , alternative = "less" , conf.level = 0.9)
#p-value la probabilité de se tromper en rejetant H0
print("----------------Q2----------------")
mm <- read.csv("data/MM.data")
prop.test(mm[1,1] , 1713 , p = 1/6)
prop.test(mm[1,2] , 1713 , p = 1/6)
prop.test(mm[1,3] , 1713 , p = 1/6)
prop.test(mm[1,4] , 1713 , p = 1/6)
prop.test(mm[1,5] , 1713 , p = 1/6)
prop.test(mm[1,6] , 1713 , p = 1/6)
print("----------------Q3----------------")
library(MASS)
t.test(immer$Y1 , immer$Y2 , paired = TRUE)
print("----------------Q4----------------")
signe <- immer$Y1-immer$Y2 < 0
succes <- sum(signe)
prop.test(succes , length(signe) , p = 0.5)
print("----------------Q5----------------")
var.test(shoes$A , shoes$B)
print("----------------Q6----------------")
t.test(shoes$A , shoes$B , var.equal = TRUE)
print("----------------Q7----------------")
shapiro.test(galaxies)
print("----------------Q8----------------")
delai <- read.csv("data/delai-data.data")
(lambda <- 1/mean(delai$delai))
ks.test(delai , "pexp" , lambda)
print("----------------Q9----------------")
glace <- data.frame(chocolat = c(100, 350), vanille = c(120, 200), fraise = c(60, 90), row.names = c("homme", "femme"))
chisq.test(glace)