##instalez le Package "Factoshiny"    mirror Canada(MB)

library(Factoshiny) 
library(FactoMineR)
library(missMDA)
library("factoextra")
library(plotrix)

library(readxl)
Tab <- read_excel("ab.xlsx")
data<-read.csv(file="ab.csv",header=TRUE,sep=";",dec=",")
data
View(Tab)
Tab_complete <- Tab[complete.cases(Tab), ]
View(Tab_complete)
Factoshiny(Tab_complete)
plot(Tab$S)  # avec x un vecteur, une liste de valeurs ex : x <- c(1:10) ; plot(x)
plot(Tab$S,Tab$AS,col="red")
plot(Tab$T,Tab$Pd,col="red")
plot(Tab$T, type = "l", lty = 2, axes = F, main = "Tail des personnes")
barplot(table(Tab$S),main="Dispertion score d'Insler")

barplot(table(Tab$PRF),col="gray",main="Distribution de la profession")
barplot(table(Tab$tabc),main="Distribution de la profession")
View(Tab$D_inf)
barplot(table(Tab$D_inf),main="Distribution de la profession")
pie(table(Tab$tabc))
View(Tab$T_inf)
pie(table(Tab$tab),main="Type d'infertilité")
pie3D(table(Tab$tab), explode = 0.1, labelcex = 0.5,main="Type d'infertilité")
pie3D(table(Tab$tabc), explode =0.5, labelcex = 1)
tab <- read_excel("abb.xlsx")
View(Tab$tab)
table(Tab$tab)

barplot(table(Tab$PRF),main="Distribution de la profession")
barplot(table(Tab$CR),main="Distribution de la profession")
barplot(table(Tab$Cell),main="Distribution de la profession")
barplot(table(Tab$ph),main="Distribution de la profession")
hist(Tab$AG, prob = TRUE,col="gray",main="Distribution de l'âge des patientes")
hist(Tab$D_inf,col="gray", prob = TRUE,main="Distribution durée d'infertilité")
barplot(table(Tab$tab),col="gray",main="Type d'infertilité")
barplot(table(Tab$tabc),col="gray",main="Type d'infection")
hist(Tab$BMI,col="gray", prob = TRUE,main="Indice de masse corporelle")
barplot(table(Tab$RE),col="gray",main="Régularité")
barplot(table(Tab$AOSG),col="gray",main="Antécédent obstétrique et gynécologique")
barplot(table(Tab$B_hor),col="gray",main="Bilan Hormonal")
barplot(table(Tab$JTPC),col="gray",main="JTPC")
barplot(table(Tab$AB_gl),col="gray",main="Abondance de la glaire")
barplot(table(Tab$CLR),col="gray",main="Couleur de la glaire")
hist(Tab$FI,col="gray", prob = TRUE,main="Filance")
barplot(table(Tab$CR),col="gray",main="Cristallisation de la glaire")
hist(Tab$ph,col="gray", prob = TRUE,main="Acidité")
barplot(table(Tab$col),col="gray",main="Le col")
hist(Tab$S,col="gray", prob = TRUE,main="Score d'Insler")
barplot(table(Tab$R_INS),col="gray",main="Résultat d'Insler")
barplot(table(Tab$A_Col),col="gray",main="Apparence du col")
barplot(table(Tab$Cell),col="gray",main="Cellularité")

barplot(table(Tab$TPC),col="gray",main="TPC")
hist(Tab$AS,col="gray", prob = TRUE,main="AS")
hist(Tab$T,col="gray", prob = TRUE,main="Taille")
dotchart(sort(Tab$AG))

hist(Tab$Pd,col="gray", prob = TRUE,main="Poids")
hist(Tab$APR,col="gray", prob = TRUE,main="APR")
hist(Tab$NJM,col="gray", prob = TRUE,main="NJM")
barplot(table(Tab$HSG),col="gray",main="HSG")
barplot(table(Tab$Y),col="gray",main="Spermogramme")
tabb <- read_excel("abb.xlsx")
summary(tabb)
pairs(tabb,main="Corrélation")
cor(tabb, method = c( "spearman"))
plot(Tab$Pd,Tab$BMI,main="Régression entre Poids et Indice de masse corporelle")
plot(Tab$BMI,Tab$T)
library(corrplot)
mcor <- cor(tabb)
corrplot(mcor, type="upper", order="hclust", tl.col="black", tl.srt=50,main="Corrélation")
library(car)
scatterplot(Tab$Pd~Tab$BMI, data=tabb, regLine=list(method=lm, lty=1, lwd=2, col="red"),main="Régression entre Poids et Indice de masse corporelle")
scatterplot(Tab$FI~Tab$S, data=tabb, regLine=list(method=lm, lty=1, lwd=2, col="red"),main="Régression entre Filance et le score d'isler")
scatterplot(Tab$D_inf~Tab$AS, data=tabb, regLine=list(method=lm, lty=1, lwd=2, col="red"),main="Régression entre durée d'infertilité et AS")
reg1 <- lm(Tab$Pd~Tab$BMI, data=tabb)
reg2 <- lm(Tab$FI~Tab$S, data=tabb)
reg3 <- lm(Tab$FI~Tab$S, data=tabb)
summary(reg1) # décris la régression
coef(reg1) # affiche les coefficients de la droite
residuals(reg1) # donne les résidus